language: php
php:
  - 7.3
  - 7.4
cache:
  directories:
    - ${HOME}/.composer/cache
before_install:
  - export PATH=$PATH:$HOME/.composer/vendor/bin
install:
  - src/Test/Script/install.sh
  - composer install --prefer-dist --no-interaction
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --ignore=*/Test/* --standard=PSR2 -p src
